root: true

env:
  browser: true
  es2021: true
  jest: true
  node: true

parser: "@typescript-eslint/parser"

parserOptions:
  project: tsconfig.json
  tsconfigRootDir: "./"
  sourceType: module

plugins:
  - "@typescript-eslint/eslint-plugin"

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

ignorePatterns:
  - ".eslintrc.js"
rules:
  "@typescript-eslint/interface-name-prefix": "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "off"
  eol-last:
    - error
    - always
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - 150
  newline-before-return: error
  no-multiple-empty-lines:
    - error
  space-before-function-paren:
    - error
    - anonymous: never
      asyncArrow: always
      named: never

# Overrides
overrides:
  [
    {
      files: ["*.ts", "*.tsx"],
      rules: { "no-undef": "off" },
      parserOptions: { project: ["./tsconfig.json"] },
    },
  ]
